apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-api
  namespace: jcu-rag-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document-api
  template:
    metadata:
      labels:
        app: document-api
    spec:
      containers:
        - name: document-api
          image: docker.io/semerb01/document-api:latest
          ports:
            - containerPort: 9090
          env:
            - name: MONGO_USER
              value: root
            - name: MONGO_PASSWORD
              value: root
            - name: MONGO_ADDRESS
              value: "mongodb://mongo-replica-set-0.mongo-is-database.mpaa.svc.cluster.local:27017"
          resources:
            requests:
              memory: "512Mi" 
              cpu: "500m"     
            limits:
              memory: "1Gi"    
              cpu: "1"       
---
apiVersion: v1
kind: Service
metadata:
  name: document-api-service
  namespace: jcu-rag-ns
spec:
  selector:
    app: document-api
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: document-api-ingress
  namespace: jcu-rag-ns
spec:
  ingressClassName: "traefik"
  rules:
    - host: jcu-document-api.com
      http:
        paths:
          - pathType: Prefix
            path: /api/data/getAll
            backend:
              service:
                name: document-api-service
                port:
                  number: 9090
          - pathType: Prefix
            path: /api/data/getLinks
            backend:
              service:
                name: document-api-service
                port:
                  number: 9090
          - pathType: Prefix
            path: /api/data/getByLink
            backend:
              service:
                name: document-api-service
                port:
                  number: 9090
            path: /api/data/
            backend:
              service:
                name: document-api-service
                port:
                  number: 9090