apiVersion: batch/v1
kind: CronJob
metadata:
  name: open-data-parser
spec:
  schedule: "0 0 1 * *"
  startingDeadlineSeconds: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: open-data-parser
        spec:
          restartPolicy: OnFailure
          containers:
            - name: open-data-parser
              image: docker.io/semerb01/open-data-parser:latest
              ports:
                - containerPort: 27017
              env:
                - name: MONGO_USER
                  value: root
                - name: MONGO_PASSWORD
                  value: root
                - name: MONGO_ADDRESS
                  value: "mongodb://mongo-service.jcu-rag-ns.svc.cluster.local:27017"
                - name: THREAD_NUMBER
                  value: "8"
                - name: SBIRKA_DOCUMENTS_NUMBER
                  value: "0"
              resources:
                requests:
                  memory: "4Gi"  
                  cpu: "4"      
                limits:
                  memory: "8Gi"    
                  cpu: "8"         