port: 7777

server:
  port: ${port}

spring:
  ai:
    #vectorstore:
    #  chroma:
    #    client:
    #      host: http://is-vector-db.dyn.cloud.e-infra.cz
    #      port: 80
    #      #key-token: <your access token (if configure)>
    #      username: <your username (if configure)>
    #      password: <your password (if configure)>
    #    initialize-schema: true
    #    collection-name: default_collection
    embedding:
      service: ollama
    ollama:
      model: Llama3.3
      init:
        pull-model-strategy: always
        embedding:
          additional-models:
            #- mxbai-embed-large
            - nomic-embed-text
        chat:
          additional-models:
            - Llama3.3
      chat:
        options:
          model: Llama3.3
        model: Llama3.3
      base-url: http://ollama.dyn.cloud.e-infra.cz/
