port: 7777

server:
  port: ${port}

vector-db:
  address: http://is-vector-db.dyn.cloud.e-infra.cz
  collection-id: f033762d-3424-4af7-815c-617b9239419e
  collection-name: SpringAiCollection

springdoc:
  api-docs:
    path: /api-docs

data-app:
  api-key: testApiKey

spring:
  ai:
    openai:
      api-key: sk-962b293a5578425784b8c4bd4ab79d09
      base-url: https://chat.ai.e-infra.cz/
      embedding:
        base-url: https://vllm.ai.e-infra.cz
        options:
          model: multilingual-e5-large-instruct
      chat:
        completions-path: /api/chat/completions
        options:
          model: llama3.3:latest
          httpHeaders:
            Authorization: Bearer sk-962b293a5578425784b8c4bd4ab79d09
